Traceback (most recent call last):
  File "start.py", line 2, in <module>
    import os, numpy
ModuleNotFoundError: No module named 'numpy'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "start.py", line 2, in <module>
    import os, numpy
ModuleNotFoundError: No module named 'numpy'
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[45512,1],0]
  Exit code:    1
--------------------------------------------------------------------------
WARNING: $PATH does not agree with $PATH_modshare counter. The following directories' usage counters were adjusted to match. Note that this may mean that module unloading may not work correctly.
 /ubda/apps/anaconda/anaconda3-2021.05//bin
